/**
 * 入金取引ファクトリー
 * @namespace transaction.deposit
 */

import { IAction as ITakeAction } from '../action/transfer/take';
import { IExtendId } from '../autoGenerated';
import { IClientUser } from '../clientUser';
import OrganizationType from '../organizationType';
import PersonType from '../personType';
import * as TransactionFactory from '../transaction';
import TransactionStatusType from '../transactionStatusType';
import TransactionTasksExportationStatus from '../transactionTasksExportationStatus';
import TransactionType from '../transactionType';

export interface IRecipient {
    typeOf: OrganizationType | PersonType;
    id: string;
    name: string;
    url: string;
}

export interface IAgent {
    typeOf: OrganizationType | PersonType;
    id: string;
    name: string;
    url: string;
}

export interface IResult {
    takeAction: ITakeAction;
}

/**
 * error interface
 * エラーインターフェース
 * @export
 * @interface
 * @memberof transaction.pay
 */
export type IError = any;

/**
 * object of a transaction interface
 * 取引対象物インターフェース
 * @export
 * @interface
 * @memberof transaction.deposit
 */
export interface IObject {
    clientUser: IClientUser;
    price: number;
    /**
     * 入金先口座ID
     */
    toAccountId: string;
    notes: string;
}

export type ITransaction = IExtendId<IAttributes>;

/**
 * 入金取引属性インターフェース
 * @export
 * @interface
 * @memberof transaction.deposit
 */
export interface IAttributes extends TransactionFactory.IAttributes {
    /**
     * 購入者
     */
    agent: IAgent;
    /**
     * 販売者
     */
    recipient: IRecipient;
    /**
     * 取引の結果発生するもの
     */
    result?: IResult;
    /**
     * 取引に関するエラー
     */
    error?: IError;
    /**
     * 取引の対象物
     * 座席仮予約、クレジットカードのオーソリなど、取引を構成する承認などが含まれます。
     */
    object: IObject;
}

/**
 * 入金取引属性を生成する
 * @export
 * @function
 * @memberof transaction.deposit
 */
export function createAttributes(params: {
    status: TransactionStatusType;
    agent: IAgent;
    recipient: IRecipient;
    result?: IResult;
    error?: IError;
    object: IObject;
    expires: Date;
    startDate?: Date;
    endDate?: Date;
    tasksExportedAt?: Date;
    tasksExportationStatus: TransactionTasksExportationStatus;
}): IAttributes {
    return {
        ...TransactionFactory.createAttributes({
            typeOf: TransactionType.Deposit,
            status: params.status,
            agent: params.agent,
            result: params.result,
            error: params.error,
            object: params.object,
            expires: params.expires,
            startDate: params.startDate,
            endDate: params.endDate,
            tasksExportedAt: params.tasksExportedAt,
            tasksExportationStatus: params.tasksExportationStatus
        }),
        ...{
            recipient: params.recipient,
            object: params.object
        }
    };
}
