/**
 * 支払アクションファクトリー
 * @namespace action.trade.pay
 */

import { ActionStatusType, ActionType, IParticipant } from '../../action';
import { IExtendId } from '../../autoGenerated';
import { IClientUser } from '../../clientUser';
import * as TradeActionFactory from '../trade';

export type IAgent = IParticipant;
export type IRecipient = IParticipant;

export interface IObject {
    transactionId: string;
    clientUser: IClientUser;
    price: number;
    accountId: string;
    notes: string;
}
export interface IResult {
    price: number;
}

export interface IAttributes extends TradeActionFactory.IAttributes {
    recipient: IRecipient;
    result?: IResult;
    object: IObject;
}

export type IAction = IExtendId<IAttributes>;

export function createAttributes(params: {
    actionStatus: ActionStatusType;
    result?: IResult;
    object: IObject;
    agent: IAgent;
    recipient: IRecipient;
    startDate: Date;
    endDate?: Date;
}): IAttributes {
    return {
        actionStatus: params.actionStatus,
        typeOf: ActionType.PayAction,
        result: params.result,
        object: params.object,
        agent: params.agent,
        recipient: params.recipient,
        startDate: params.startDate,
        endDate: params.endDate
    };
}
